### ISSUE TITLE
Spark user creation is not working

### ISSUE THREAD

**Issue by belykhk** [belykhk/castopod-ansible-playbook#1]
Since changing auth library in castopod from `myth-auth` to `shield`, there is no current way to create superuser within ssh session (and in consequence with ansible). Currently playbook throws error similar to this:

```
$ php spark auth:create_user

CodeIgniter v4.2.7 Command Line Tool - Server Time: 2023-07-22 10:08:43 UTC+00:00

Command &quot;auth:create_user&quot; not found.
```

Currently waiting for this [issue](https://github.com/codeigniter4/shield/issues/566) and [pull request](https://github.com/codeigniter4/shield/pull/579) to be merged

**Comment by yassinedoghri** [comment]
Good news: the feature has been [merged into develop](https://github.com/codeigniter4/shield/pull/833) and the issue was closed!

Awaiting for a release to update Castopod.
