### ISSUE TITLE
admin user page 403 no permission

### ISSUE THREAD

**Issue by OhCoder** [belykhk/castopod-ansible-playbook#4]
### Help! I love Fediverse!

system: Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-91-generic x86_64)

except the cp-admin page, all is 403 no permission.

**this is the cp-admin page.**
![Xnapper-2024-01-13-19 44 54](https://github.com/belykhk/castopod-ansible-playbook/assets/890676/c7f81e49-7009-48e9-aa8b-d70615828747)

**this is the cp-admin/settings page**
![Xnapper-2024-01-13-19 46 39](https://github.com/belykhk/castopod-ansible-playbook/assets/890676/177249ab-c8b7-4adf-bd9f-79e84f8b71cf)

### Install info:
according to the [inventory.yml](https://github.com/belykhk/castopod-ansible-playbook/blob/main/inventory.yml.example) file install, no error, and set the castopod_username, castopod_email, castopod_password.

after successful installed, login succeed, but no permission.

**here is cp_users data**
![Xnapper-2024-01-13-19 53 13](https://github.com/belykhk/castopod-ansible-playbook/assets/890676/8633ef81-e882-4989-84ae-45c9f1d4d1d6)

**here is cp_auth_permissions_users data**
<img width="669" alt="Xnapper-2024-01-13-19 55 41" src="https://github.com/belykhk/castopod-ansible-playbook/assets/890676/acc112dd-78a6-4195-a629-09ef3dc75edb">

**cp_auth_groups_users data**
<img width="553" alt="Xnapper-2024-01-13-19 57 09" src="https://github.com/belykhk/castopod-ansible-playbook/assets/890676/b7a8f6b3-156a-4260-9c4e-919b45a060a7">

**Comment by belykhk** [comment]
Fixed on castopod's side with release of 1.8.0
